### ISSUE TITLE
SHUIWIFI.bin

### ISSUE THREAD

**Issue by ange007** [vyacheslav-shubin/shui#2]
Добрый день.
Не могу понять как прошить WiFi модуль на сапфире, файл указанный в readme _(SHUIWIFI.bin)_ - отсутствует.
В данный момент - WiFi не находит сети.

**Comment by ange007** [comment]
Взял файл со старых архивов. Но прошивка не проходит.
На первом этапе там где синхронизация по UART - Failed.

**Comment by vyacheslav-shubin** [comment]
https://t.me/joinchat/8eQiBVI29zw1YTU6 
Заходите в группу
